version: '3.8'
services: 
    orders-service:
        build: .
        container_name: pad-orders-service
        ports: ['8000:8000']
        environment:
            - IP=orders-service
            - PORT=8000
        command: sh -c "ruby main.rb"